1 : System.out.print("Hello World");
   2 : System.out.print("Hello World");
   3 : System.out.print("Hello Shivendra")
   4 : System.out.print("Hello! How are you doing")
   8 : System.out.print("myFirstNumber");
   9 : System.out.print(myFirstNumber);
  11 : System.out.print(myFirstNumber);
  12 : myFirstNumber = 10 + 5 + 8;
  13 : myFirstNumber = (10 +5) + (2 * 10);
  14 : int myFirstNumber = (10 + 5) + (2 * 10);
  15 : int mySecondNumber = 12;
  16 : int myThirdNumber = 6;
  18 : myThirdNumber = myFirstNumber * 2
  19 : myTotal = myFirstNumber + mySecondNumber + myThirdNumber
  20 : int myLastOne = 1000 - myTotal;
  21 : System.out.print(myLastOne)
  22 : int myMinValue = Integer.MIN_VALUE;
  23 : int myMaxValue = Integer.MAX_VALUE;
  24 : System.out.print("Integer Minimum Value = " + myMinValue);
  25 : System.out.print("Integer Minimum Value = " + myMaxValue);
  26 : System.out.print("Integer Minimum value = " + Integer.MIN_VALUE + "to " + Integer.MAX_VALUE + ")" );
  27 : System.out.print("Integer Minimum value = " + Integer.MIN_VALUE + "to " + Integer.MAX_VALUE + ")" );
  28 : System.out.print("Integer Minimum value = " + Byte.MIN_VALUE + "to " + Byte.MAX_VALUE + ")" );
  29 : System.out.print("Integer Minimum value = " + Byte.MIN_VALUE + " to " + Byte.MAX_VALUE + ")" );
  30 : System.out.print("Integer Minimum value = " + Short.MIN_VALUE + " to " + Short.MAX_VALUE + ")" );
  31 : System.out.print("Short Minimum value = " + Short.MIN_VALUE + " to " + Short.MAX_VALUE + ")" );
  32 : long myLongValue = 100L;
  33 : System.out.print("A long has a width of " + Long.SIZE);
  34 : System.out.print("Long Value Range (" + Long.MIN_VALUE + " to " + Long.MAX_VALUE + ")");
  35 : myLongValue = 100;
  36 : long bigLongLiteralValue = 2_147_483_647;
  37 : short myMinShort = Short.MIN_VALUE;
  38 :  int myMinInterger = Integer.MIN_VALUE;
  40 :  int myByteInterger = Byte.MIN_VALUE;
  41 : byte  myMinByte = Byte.MIN_VALUE;
  42 :  int myMaxByte = Byte.MAX_VALUE;
  43 : short firstShort = 1;
  44 :  int firstinterger = 2;
  45 : byte firstByte = 1, secondByte = 2;
  46 : byte firstByte = 1, secondByte = 2;
  48 : int myTotal = (myMinByte / 2);
  49 : byte myNewByteValue = (byte)(myMinByte / 2);
  50 : short myNewShortValue = (short)(myMinShort/2);
  51 : byte byteValue = 10;
  52 : short shortValue = 20;
  53 : int intValue = 50;
  54 : long longValue = 50000L + 10L * (byteValue + shortValue + intValue);
  55 : int sumOfThree =  byteValue + shortValue + intValue;
  56 : long longTotal = 50000L + (10 * sumOfThree);
  58 : int myIntValue = 5;
  59 : float myFloatValue = 5f;
  60 : double myDoubleValue = 5d;
  61 : myIntValue = 5/2;
  62 : myFloatValue = 5f / 2f;
  63 : myDoubleValue = 5d / 2d;
  64 : myIntValue = 5 / 3;
  65 : myFloatValue = 5f / 3f;
  66 : myDoubleValue = 5d / 3d;
  67 : myDoubleValue = 5.00 / 3;
  68 : double myNumber = 40.3482991;
  69 : double myNumberKg = myNumber * 0.45359237;
  70 : double numberOfPound = 200d;
  71 : double numberOfKg = numberOfPound * 0.45359237;
  72 : System.out.print("Converted Kilogram = " + numberOfKg );
  73 : double pi = 3.1415927d;
  75 : char myChar = 'D';
  76 : char myUnicode = '\u0045';
  77 : char myDecimal = 69;
